---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: concourse-pipelines

params:
  APP_NAME:
  CF_API_URL:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:

run:
  path: concourse-pipelines/tasks/validate-app/task.sh