cf-api-url: CHANGEME
cf-apps-url: CHANGEME
cf-username: CHANGEME
cf-password: CHANGEME
cf-org: CHANGEME
cf-space: CHANGEME
git-username: CHANGEME
git-password: CHANGEME
artifactory-endpoint: CHANGEME
artifactory-username: CHANGEME
artifactory-password: CHANGEME
artifactory-java-app-repo: CHANGEME
artifactory-java-app-regex: CHANGEME
concourse-pipelines-repo: CHANGEME
cf-test-app-staticfile-repo:  CHANGEME
cf-test-app-ruby-repo: CHANGEME
cf-test-app-nodejs-repo:  CHANGEME
cf-test-app-go-repo:  CHANGEME
cf-test-app-php-repo:  CHANGEME
cf-test-app-binary-repo:  CHANGEME
cf-test-app-python-repo: CHANGEME
cf-test-app-java-repo:  CHANGEME
cf-test-app-dotnet-repo:  CHANGEME